import type { WeekEntry } from '../types';

export const weeks: WeekEntry[] = [
  { week: 0, title: 'First meeting', note: 'For now, the world is scent, warmth and the voice he heard even before birth.' },
  { week: 1, title: 'Everything is very close', note: 'He can see about 25 centimetres — just as far as your face when you hold him.' },
  { week: 2, title: 'A familiar voice', note: 'At a familiar voice, he becomes still and listens. This is his first kind of attention.' },
  { week: 3, title: 'Pauses appear', note: 'Between sleep and tears, brief calm minutes appear. This is his first awake time.' },
  { week: 4, title: 'His gaze lingers', note: 'He looks at one spot for longer and longer, most often at a face.' },
  { week: 5, title: 'Senses sharpen', note: 'The world suddenly feels brighter and louder than yesterday. There may be more tears — it is not about you.' },
  { week: 6, title: 'First smile back', note: 'A smile is no longer accidental: he smiles especially at you and waits for one in return.' },
  { week: 7, title: 'Sounds become a conversation', note: 'Vowel sounds appear — “aaa”, “eee”. If you answer, he will carry on.' },
  { week: 8, title: 'The world breaks into details', note: 'He begins to notice patterns and edges, and studies them for a long time.' },
  { week: 9, title: 'Hands discovered', note: 'His own hands are this week’s most interesting toy. He looks at them and tastes them.' },
  { week: 10, title: 'A steadier head', note: 'On his tummy, he lifts his head and looks around — his view of the world has changed.' },
  { week: 11, title: 'Laughter', note: 'Real laughter appears in response to play. He already understands that funny things can happen again.' },
  { week: 12, title: 'Reaching and grasping', note: 'Hand and eye have begun to work together: he does not only look, he takes.' },
  { week: 13, title: 'Cause and effect', note: 'He notices: I touched it, and it rang. It is the first experiment of his life.' },
  { week: 14, title: 'The world gains depth', note: 'He has begun to see depth, reaching for what he once only watched.' },
  { week: 15, title: 'Everything goes in the mouth', note: 'His mouth is now his main way of exploring, more sensitive than his fingers. It is exploration, not hunger.' },
  { week: 16, title: 'Turning towards a voice', note: 'He finds the source of a sound and turns towards it — hearing and movement have met.' },
  { week: 17, title: 'Rolling is close', note: 'His body is rehearsing a roll: he rocks on his side and gets cross when it does not work yet.' },
  { week: 18, title: 'The give-and-take game', note: 'He gives you an object and waits for you to return it. It is his first wordless conversation.' },
  { week: 19, title: 'His voice as a toy', note: 'Squeals, gurgles, whispers — he is trying out what his own mouth can do.' },
  { week: 20, title: 'Sitting with support', note: 'From a sitting position the world looks different, and his hands are finally free.' },
  { week: 21, title: 'Familiar and unfamiliar', note: 'He can now tell familiar people from strangers and may be wary of someone new.' },
  { week: 22, title: 'Syllables', note: '“Ba”, “ma”, “da” appear — not aimed at anyone yet, simply sounds he enjoys.' },
  { week: 23, title: 'Passing from hand to hand', note: 'His two hands have begun to make arrangements with each other.' },
  { week: 24, title: 'Interest in grown-up food', note: 'He watches your plate and reaches for the spoon — it is about copying you.' },
  { week: 25, title: 'Things still exist', note: 'He begins to suspect that something put away has not vanished — it is somewhere.' },
  { week: 26, title: 'Half a year', note: 'He sits, turns to his name and distinguishes tones of voice. Half a year is a noticeable landmark.' },
  { week: 27, title: 'Hide and find', note: 'Peekaboo is now both the finest entertainment and real work for his memory.' },
  { week: 28, title: 'Moving forward', note: 'He twists, pushes off and inches towards a goal — for now, the way he gets there can be any way at all.' },
  { week: 29, title: 'Testing what things can take', note: 'Dropping, banging, shaking — this is how he finds out what the world is made of.' },
  { week: 30, title: 'Understanding tone', note: 'The meaning of words is still far away, but he reads warmth or worry in a voice exactly.' },
  { week: 31, title: 'Worry at parting', note: 'He may cry when you leave the room. It is not fussiness — it is attachment.' },
  { week: 32, title: 'Pincer grip', note: 'Thumb and forefinger are learning to pick up a crumb. Fine motor skills are growing.' },
  { week: 33, title: 'Imitation', note: 'He repeats your gestures and sounds — that is how he learns most quickly.' },
  { week: 34, title: 'Pulling up at support', note: 'Holding the sofa, he pulls himself up. Getting down is harder than getting up for now.' },
  { week: 35, title: 'His own name', note: 'He responds confidently to his name and looks for the person who called.' },
  { week: 36, title: 'Categories', note: 'He begins to notice that things can be alike: all balls roll, all spoons chime.' },
  { week: 37, title: 'Pointing', note: 'He points with a finger and looks at you: “Can you see what I see?”' },
  { week: 38, title: 'First rules', note: 'He understands a short “no”, though for now he is more likely to test whether it still works.' },
  { week: 39, title: 'Moving along furniture', note: 'Holding on, he travels along the sofa — whole routes around the home.' },
  { week: 40, title: 'Putting in and stacking', note: 'Putting one thing inside another is more interesting than any toy — he is sorting out sizes.' },
  { week: 41, title: 'First words for someone', note: '“Mum” or “Dad” begin to belong to a particular person.' },
  { week: 42, title: 'Giving and asking', note: 'He holds out a thing for you to take, and reaches out when he wants it back.' },
  { week: 43, title: 'Sequences', note: 'He anticipates what comes next: bath, pyjamas, story. Routines have become a support.' },
  { week: 44, title: 'Mood feels shared', note: 'He notices your emotions and catches them. A calm grown-up soothes more quickly than words.' },
  { week: 45, title: 'Standing unsupported', note: 'A few seconds without hands — and he is surprised himself.' },
  { week: 46, title: 'Trying a spoon', note: 'Eating by himself is messy and slow for now, but it is about independence, not food.' },
  { week: 47, title: 'Understanding more than he says', note: 'He already follows simple requests, though he has hardly any words yet.' },
  { week: 48, title: 'First steps', note: 'Steps may begin this week, or three months from now — the range is wide.' },
  { week: 49, title: 'Playing alongside', note: 'Other children interest him, but for now he plays alongside them rather than with them — as he should.' },
  { week: 50, title: 'Wishes of his own', note: 'He makes it clear what he wants and gets upset when he cannot make himself understood.' },
  { week: 51, title: 'Remembering yesterday', note: 'He remembers where a toy was yesterday and goes there.' },
  { week: 52, title: 'One year', note: 'A year has passed. He is already a person with character, preferences and his own opinion about soup.' },
];

export const weekFallback: WeekEntry = {
  week: -1,
  title: 'Every week is its own',
  note: 'He grows at his own pace — and that is all right.',
};
